### ISSUE TITLE
/sbin/ip is missing

### ISSUE THREAD

**Issue by xtagon** [fauria/docker-vsftpd#11]
Hi,

If you don't specify a the `PASSV_ADDRESS` environment variable, the following error appears in the logs:

```
/usr/sbin/run-vsftpd.sh: line 27: /sbin/ip: No such file or directory
```

It looks like the `iproute` package isn't installed.

**Comment by srl295** [comment]
`/sbin/ip` is such a heavyweight operation you know.

I hacked around this by parsing `/etc/hosts` to extract the IP. I couldn't avoid `500 OOPS: invalid pasv_address` otherwise.

**Comment by xtagon** [comment]
Yeah it's not hard to work around, but it was pretty confusing at first.

**Comment by CyberJack** [comment]
I just created a pull request for this. [#46](https://github.com/fauria/docker-vsftpd/pull/46)

**Comment by fauria** [comment]
PR #46 merged.
