### ISSUE TITLE
Wrong volume is mounted by default

### ISSUE THREAD

**Issue by oche-jay** [fauria/docker-vsftpd#13]
First of all thanks for this, saved me a few hours of doing the dockerisation myself. 

The issue here is that the 'production' setup doesn't work out of the box. Since I am mounting a volume 'my/volume/here' to 'home/vsftp', the expectation is that the default config should be set to mount that volume, and not /home/vsftp/user which is set in the default config.

**Comment by nuKs** [comment]
Thanks for the comment! Made me gain some time.

Also, docker image is `fauria/vsftpd` and not `fauria/lap`.

Would be nice to fix the doc.

**Comment by fauria** [comment]
PR merged.
