### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ruddhani** [fauria/docker-vsftpd#14]
its a centos 7 docker image from repo fauria/docker-vsftpd, run as :

docker run -d -p 21:21 -p 20:20 -p 21100-21110:21100-21110 -v /mydir:/home/vsftpd -e FTP_USER=myuser -e FTP_PASS=mypass -e PASV_ADDRESS=127.0.0.1 -e PASV_MIN_PORT=21100 -e PASV_MAX_PORT=21110 --name myvsftpd --restart=always fauria/vsftpd

Unable to login to ftp via filezilla: details are :

host: 192.168.99.100
port: 21
protocol: sftp
logon type: normal
user: myuser
pass: mypass

Suggestion if any,

Thanks,
Aniruddha
--

**Comment by urimiller** [comment]
try protocol ftp instead of sftp
