### ISSUE TITLE
can not login with new add FTP user 

### ISSUE THREAD

**Issue by CocaChen** [fauria/docker-vsftpd#17]
i tried add a new ftp user,but login failed

finallly , i find the solution 

```bash
# 4) Manually add a new FTP user to an existing container:
docker exec -i -t vsftpd bash
mkdir /home/vsftpd/myuser
chown -R ftp:ftp /home/vsftpd
echo -e "myuser\nmypass" >> /etc/vsftpd/virtual_users.txt
/usr/bin/db_load -T -t hash -f /etc/vsftpd/virtual_users.txt /etc/vsftpd/virtual_users.db
exit
docker restart vsftpd
```
you should add `chown -R ftp:ftp /home/vsftpd` command

**Comment by fauria** [comment]
Owners set on [Dockerfile](https://github.com/fauria/docker-vsftpd/blob/db30088be86790c566bdb528e20b1ad0de3d1edd/Dockerfile#L39).

**Comment by mrigi** [comment]
Hey, "chown -R ftp:ftp /home/vsftpd" is absolutely unacceptable. Just imagine someone mount a whole volume to a /home/vsftpd/{SOME_USER} and you override all the rights inside. What? Why?! If for example you add ftp access to web root and override owner this brutal way most web sites will be completely broken. Never do that recursive chown. Fix ASAP plz.
