### ISSUE TITLE
Passive mode is not working

### ISSUE THREAD

**Issue by P9110963** [fauria/docker-vsftpd#18]
Hi,

When I connected from FileZilla in passive mode I'm getting the below error.  I have used the same settings as given in the repo. 
Error:	Disconnected from server: ECONNABORTED - Connection aborted
Error:	Failed to retrieve directory listing

Note: Active mode is working fine without any issue. But need to understand what is blocking the passive mode.

**Comment by P9110963** [comment]
Note: I'm running this in Azure vm.. does this support passive mode?

**Comment by THLIVSQAZ** [comment]
I got the same error,I run in vmware

**Comment by THLIVSQAZ** [comment]
I found the problem, passive mode ip address must you vps's ip

**Comment by StartAt24** [comment]
> I found the problem, passive mode ip address must you vps's ip
hello, i got the same same error. What do  you mean by "vps's ip"?
what should i define "-e PASV_ADDRESS" ？
“0.0.0.0” or "127.0.0.1" doesn't work.

**Comment by THLIVSQAZ** [comment]
yeah the 0.0.0.0 and 127.0.0.1 doesn't work ,passive mode will return an ip to the client ,let client to use this ip connect server,so the ip must accessible connection from the external network

**Comment by chestercs** [comment]
Hello. This happened me too over the internet connection, 
and found the solution for it.
You need to change this line in the config file to YES
`pasv_addr_resolve=YES`

then you can use  PASV_ADDRESS env with your domain name to reach your ftp server over the internet.
Also make sure to do the port forwarding properly. This is valid for Virtual enviroments aswell like vmware

**Comment by fauria** [comment]
PR merged.
