### ISSUE TITLE
Windows client how to control the Linux host to run the program？

### ISSUE THREAD

**Issue by 408550969** [fauria/docker-vsftpd#25]
I want to control the linux system running program on MFC (for example, .sh file),How to achieve it?
I know that you can use the "quote site exec ***.exe" command to run the windows server program, but this code does not work under the Linux system.

**Comment by fauria** [comment]
I would suggest having a look at Docker's documentation for this: [Get started with Docker for Windows
](https://docs.docker.com/docker-for-windows/).
