### ISSUE TITLE
Error during connection

### ISSUE THREAD

**Issue by alessandrolattao** [fauria/docker-vsftpd#26]
Hello,
first of all I want to thank you for this container, we are using it since a couple of years and it works pretty well.

We are having a problem with the last update, when we try to connect to the server it says "500 OOPS: failed to open xferlog log file:/var/log/vsftpd/vsftpd.log".

Deleting /var/log/vsftpd/vsftpd.log solves the problem.

Thank you again

**Comment by fauria** [comment]
Hi! 

Thank you very much, I'm glad you find this useful. Fixed [xferlog_std_format](https://github.com/fauria/docker-vsftpd/commit/db30088be86790c566bdb528e20b1ad0de3d1edd).

Cheers!
