### ISSUE TITLE
Document the permissions change

### ISSUE THREAD

**Issue by Yamp** [fauria/docker-vsftpd#32]
I know, that It's my stupidity, but I've mounted my VPS' root dir inside the container, and it's started to change my files permissions recursively. Which of course led to the fatal system corruption. So I believe this behaviour should be documented somewhere...

**Comment by fauria** [comment]
There are no permission changes done here, just [ownership of home directory](https://github.com/fauria/docker-vsftpd/blob/master/run-vsftpd.sh#L22). Not sure about the side effects you're experiencing after mounting `/`.

**Comment by etcho** [comment]
Same thing happened to me. I even lost ssh access to my server due to this ownership issue. Since it's a headless server, it will be a pain to regain access and discover what happened. I think it changed not only the permissions on my home folder.
