### ISSUE TITLE
When the container is restarted, the ‘virtual_users.txt’ is reset

### ISSUE THREAD

**Issue by joke3306** [fauria/docker-vsftpd#36]
ubuntu 16.04
image version:latest
command:
>docker run -d -v /my/data/directory:/home/vsftpd \
-p 20:20 -p 21:21 -p 21100-21110:21100-21110 \
-e FTP_USER=myuser -e FTP_PASS=mypass \
-e PASV_ADDRESS=127.0.0.1 -e PASV_MIN_PORT=21100 -e PASV_MAX_PORT=21110 \
--name vsftpd --restart=always fauria/vsftpd

---
I modified the file '/etc/vsftpd/virtual_users.txt’, but when the container restarted, it was reset.
Please help me.

**Comment by good-and-more** [comment]
I met the same thing, I run docker restart vsftpd, and the file '/etc/vsftpd/virtual_users.txt' was reset, and the vsftpd.conf append like this
![vsftpd conf](https://user-images.githubusercontent.com/29789043/109625454-5360a000-7b7a-11eb-9adb-5254d56b1a93.png)
