### ISSUE TITLE
Container does not work with safe user (ftp)

### ISSUE THREAD

**Issue by pansa** [fauria/docker-vsftpd#38]
Container does not start if use "ftp" user:

...
/usr/sbin/run-vsftpd.sh: line 24: /etc/vsftpd/virtual_users.txt: Permission denied
BDB5072 db_load: /etc/vsftpd/virtual_users.txt: reopen: No such file or directory

because of:
    24	echo -e "${FTP_USER}\n${FTP_PASS}" > /etc/vsftpd/virtual_users.txt
can't write to file
-rw-r--r--. 1 root root    30 Aug 28 12:42 virtual_users.txt

**Comment by fauria** [comment]
Please, refer to vsftpd documentation: https://security.appspot.com/vsftpd.html

**Comment by xTey** [comment]
Experiencing the same issues. Any solution @pansa ?
