### ISSUE TITLE
Run vsftpd as standalone

### ISSUE THREAD

**Issue by HamzaDevz** [fauria/docker-vsftpd#50]
Thanks for this image !

My goal is to have this container always open, and to have only "virtual_users.txt" updated by our application.

So, it would be great to launch vsftpd as a service.

When trying to start it with systemctl I have this error : 

`[root@d865273a4eae init.d]# systemctl start vsftpd.service
Failed to get D-Bus connection: Operation not permitted`

I want to have it as standalone to be able to restart it when the file "virtual_users.txt" is updated with a cron.

Do you have an idea ?
Thank you by advance.

**Comment by fauria** [comment]
I'm not sure I understand this request. Is there any reason for not restarting the container itself?

**Comment by HamzaDevz** [comment]
Avoiding killing users which are transferring files ?

**Comment by fauria** [comment]
I think you are mistaking restarting with reloading (your request is about the former). In any case, I think service management should be done outside the container. If you are interested in using `systemd`, I'd recommend having a look at https://hub.docker.com/_/centos section *Running a systemd enabled app container*.
