### ISSUE TITLE
Still not fixed!!!!!!

### ISSUE THREAD

**Issue by zl910627** [fauria/docker-vsftpd#58]
https://github.com/fauria/docker-vsftpd/issues/1

![image](https://user-images.githubusercontent.com/53897531/94700568-35460800-036e-11eb-887d-ff220452f8a7.png)

![image](https://user-images.githubusercontent.com/53897531/94700699-5ad31180-036e-11eb-90dc-6e2da32babdd.png)

**Comment by zl910627** [comment]
PS: I have turnoff firewall on my Mac.
I never get it working!

**Comment by MikeReh** [comment]
Same problem here

**Comment by waqasraz** [comment]
```docker run -d -p 2021:21 -p 21100-21110:21100-21110 -e FTP_USER=myuser -e FTP_PASS=mypass -e PASV_ADDRESS=127.0.0.1 -e PASV_MIN_PORT=21100 -e PASV_MAX_PORT=21110 -e LOCAL_UMASK=0777 -e PASV_ADDRESS_ENABLE=YES -v /Users/user/Documents:/home/vsftpd --name vsftpd fauria/vsftpd ```

This made the connection successful on MAC

**Comment by jarne-vs** [comment]
I don't know if there are still problems with this but the thing that worked for me was setting the PASV_ADDRESS to the ip of the server it needs to connect to.
