### ISSUE TITLE
Cant write (553 filezilla ) files in directory, mounted by cifs(ftp ftp owner 755 permission)

### ISSUE THREAD

**Issue by shabadin** [fauria/docker-vsftpd#60]
I have windows host's shared folder mounted by cifs to linux vm guest, which s runnin docker container(/home/user/conf/folder) i can easily do anything to drag, upload, download or any other kind of interraction( from both side either host windows or guest vm ubuntu).
On vm i have docker container:run command looks like " docker run -v /home/user/conf/folder:/home/vsftpd/user -p 20:20 -p 21:21 -p 47400-47040:47400-47040 -e FTP_USER  "ftp" -e FTP_PASS "ftp" -e PASS_ADDRESS="ip host"  -d fauria/docker-vsftpd. It starts correctly, so i can connect to host ip using ftp:ftp  user:pass combo with filezilla ftp protocol.I can even download any file from mounted dir(and it is really mounted, because i can see all files from host), but cant upload or change(755 perm). My mounted folder owned by user ftp:ftp which was made by myself and has 1002:1002 uid:gid.

P.s. on the same vm i have runnable docker  sftp container by atmoz which have absolutely 0 issues even w/custom ssh keys

Can u help me please. How can i solve this problem?

**Comment by liangbinc** [comment]
what the reason

**Comment by mmtzwyd** [comment]
still exists
